name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_preentrega
      id: test_preentrega
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_preentrega
        setup-command: pip install pytest
        command: pytest test/test_preentrega.py
        timeout: 20
        max-score: 100
    - name: test_preentrega1
      id: test_preentrega1
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_PREENTREGA_RESULTS: "${{steps.test_preentrega.outputs.result}}"
        TEST_PREENTREGA1_RESULTS: "${{steps.test_preentrega1.outputs.result}}"
      with:
        runners: test_preentrega,test_preentrega1
